pymwp/polynomial.py
and remove method because it is not used elsewhere and its naming is confusing
=> inline multiply 

docs/matrix.md, pymwp/matrix.py, tests/test_matrix.py
This changeset includes what was listed in issue #12.
=> Additional methods for the Matrix

docs/features.md, mkdocs.yml
At some point I was asked to make this list (for tool paper), so I create this document as a reference summary. It is for the [docs website](https://seiller.github.io/pymwp/) but once I have it written down, I can add to the paper.
I believe I have fully captured everything we can do in the implementation at the moment. It should also include most of the planned features, but I may have missed some? Please review.
=> Supported language features

docs/assets/demo.html, docs/demo.md
Added: request timeout, progress bar, some explanation around what the output means.
=> Add some polish and explanation to demo page

c_files/original_paper/example3_1_a.c, c_files/original_paper/example3_1_b.c, c_files/original_paper/example3_1_c.c, c_files/original_paper/example3_1_d.c, c_files/original_paper/example3_2.c, c_files/original_paper/example3_4.c, c_files/original_paper/example5_1.c, c_files/original_paper/example7_10.c, c_files/original_paper/example7_11.c, c_files/readme.md
Sorry, I've pushed in this branch, forgetting it had been merged.
I will delete it after merging.
=> Tests examples

pymwp/polynomial.py, tests/test_polynomial.py
=> fix times order #45

pymwp/analysis.py, tests/mocks/ast_mocks.py, tests/mocks/params.c, tests/test_analysis.py
This change looks for declarations in function param list
=> Declarations in param list (#51)

pymwp/__main__.py, pymwp/analysis.py, pymwp/monomial.py, pymwp/polynomial.py, pymwp/relation_list.py, tests/mocks/ast_mocks.py
simplify create_vector; update docsstrings
=> refactor and simplify analysis methods

pymwp/delta_graphs.py, pymwp/monomial.py
this is an old alias of monomial.deltas it can be removed now
=> refactor monomial.list

Makefile, utilities/profiler.py
=> edit profiler

pymwp/analysis.py
=> change vector

pymwp/__main__.py, pymwp/analysis.py
This PR adds an argument that computes the matrix even if failure is detected.
=> Compute matrix

c_files/implementation_paper/example14.c, c_files/implementation_paper/example16.c, c_files/implementation_paper/example8.c, c_files/readme.md, tests/mocks/ast_mocks.py, tests/test_parser.py
=> fix: example names

Makefile, docs/file_io.md, docs/utilities.md, pymwp/analysis.py, pymwp/bound.py, pymwp/file_io.py, pymwp/result.py, requirements-dev.txt, tests/test_file_io.py, utilities/ast_util.py, utilities/plot.py, utilities/profiler.py
Tooling to generate table of results.
=> Evaluation

README.md, docs/utilities.md, requirements-dev.txt, requirements-test.txt
separate test vs. docs packages
=> small dependency reorg

pymwp/__init__.py, setup.py
=> version bump

docs/assets/demo.html, docs/assets/styles.css
change from result triple -> `Result` object
=> update demo front-end

.zenodo.json, CITATION.cff, pymwp/__init__.py, pymwp/__main__.py, pymwp/analysis.py, pymwp/bound.py, pymwp/choice.py, pymwp/constants.py, pymwp/delta_graphs.py, pymwp/file_io.py, pymwp/matrix.py, pymwp/monomial.py, pymwp/parser.py, pymwp/polynomial.py, pymwp/relation.py, pymwp/relation_list.py, pymwp/result.py, pymwp/semiring.py, setup.py
which requires adding these notices, see:
* https://www.gnu.org/licenses/gpl-howto.html
* https://www.gnu.org/licenses/identify-licenses-clearly.html
=> properly apply GPL

docs/features.md, pymwp/analysis.py
Enhancement to include unary operators.
=> Unary operators

.github/workflows/build.yaml, .github/workflows/docs.yaml, .github/workflows/publish.yaml, .github/workflows/pyversion.yaml
=> bump workflow actions checkout v3+python v4 => v4/v5

.github/workflows/build.yaml, pymwp/analysis.py, requirements-dev.txt
fix for "indented line-wrap breaks docs" + add future sanity test for this for PRs.
=> docstring linewrap fix

pymwp/__init__.py, pymwp/__main__.py, pymwp/analysis.py, pymwp/base.py, pymwp/delta_graphs.py, pymwp/parser.py, pymwp/result.py, pymwp/syntax.py, tests/test_analysis.py, tests/test_file_io.py, tests/test_matrix.py, tests/test_parser.py, tests/test_polynomial.py, tests/test_relation.py
enhancements to work with input syntax
=> syntax checks

pymwp/bound.py, pymwp/syntax.py, tests/test_bound.py
=> Bound eq comparison

pymwp/analysis.py, pymwp/file_io.py, pymwp/syntax.py, tests/test_analysis.py, tests/test_parser.py
tests for ast nodes
use strict tests not deepcopy
skip assert
=> small fixes

pymwp/choice.py
=> choice right reduce

pymwp/analysis.py, tests/test_analysis.py
Incrementing the index creates unnecessary choices when it is just one choice.
=> single variable assignment

docs/assets/styles.css, docs/choice.md, pymwp/choice.py, tests/test_choices.py
=> choice docs

pymwp/choice.py
=> choice improvement

docs/choice.md, pymwp/__init__.py, pymwp/analysis.py, pymwp/choice.py, pymwp/monomial.py, pymwp/polynomial.py, pymwp/semiring.py, pymwp/syntax.py, tests/test_analysis.py
move type hints, use flow variables.
=> various small edits

pymwp/polynomial.py, pymwp/relation.py
Make eval callable with scalars.
=> eval with scalars

docs/utilities.md, utilities/runtime.py
=> machine details

pymwp/__main__.py, pymwp/analysis.py
It is not needed for anything.
=> remove `--no_eval`

pymwp/analysis.py, pymwp/parser.py, pymwp/syntax.py, tests/test_parser.py
=> edit parser and syntax

pymwp/analysis.py, tests/test_loop_analysis.py
Include loop guard in variables to evaluate
=> include loop guard

pymwp/analysis.py, pymwp/result.py
Record number of functions and loops even if unsupported.
Round ms time before truncate.
=> add counters of functions and loops

pymwp/syntax.py, tests/test_coverage.py
=> syntax analysis fix

pymwp/analysis.py, pymwp/parser.py, pymwp/result.py, pymwp/syntax.py, tests/test_coverage.py, tests/test_find_loops.py, tests/test_variables.py
improve loop form recognition
on some conditions translate for to while
count loops, for loops in program
=> edits to loop handling
